spring.application.name=Ignitiv_Project

kibo.tenant-id=52670
kibo.site-id=78211
kibo.client-id=1908
kibo.client-secret=db56ada674e74352aa5154b0de3f745d
kibo.tenant-host=t52670.sandbox.mozu.com
kibo.home-host=home.mozu.com


executor.corePoolSize=50
executor.maxPoolSize=50
executor.queueSize=1000
executor.keepAliveSeconds=60